use_frameworks!

platform :ios, '10.0'

target 'MapboxVisionNativeAll_Example' do
  pod 'MapboxVisionNativeAll', :path => '../'

  target 'MapboxVisionNativeAll_Tests' do
    inherit! :search_paths

    
  end
end
